# Embed ggml-metal.metal for desktop sidecar builds.
# Same as ios/metal-embed.cmake but paths are relative to this repo root.

set(SOURCE_DIR "${ANNADATA_CPP_DIR}")
set(METALLIB_COMMON "${SOURCE_DIR}/ggml-common.h")
set(METALLIB_SOURCE "${SOURCE_DIR}/ggml-metal.metal")
set(METALLIB_IMPL "${SOURCE_DIR}/ggml-metal-impl.h")
set(METALLIB_EMBED_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/../ios/embed-metal-shaders.sh")

file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/autogenerated")

set(METALLIB_EMBED_ASM "${CMAKE_CURRENT_BINARY_DIR}/autogenerated/ggml-metal-embed.s")
set(METALLIB_SOURCE_EMBED "${CMAKE_CURRENT_BINARY_DIR}/autogenerated/ggml-metal-embed.metal")

add_custom_command(
    OUTPUT "${METALLIB_EMBED_ASM}"
    COMMAND "${METALLIB_EMBED_SCRIPT}"
        "${METALLIB_COMMON}"
        "${METALLIB_SOURCE}"
        "${METALLIB_IMPL}"
        "${METALLIB_EMBED_ASM}"
        "${METALLIB_SOURCE_EMBED}"
    DEPENDS
        "${METALLIB_EMBED_SCRIPT}"
        "${METALLIB_COMMON}"
        "${METALLIB_SOURCE}"
        "${METALLIB_IMPL}"
    COMMENT "Generate assembly for embedded Metal shader source (desktop sidecar)"
    VERBATIM
)
